ae/urls.py
from django.urls import path

from . import views as v


app_name = "ae"

urlpatterns = [
    # url(r"daily-cash-record/$", cash_records.daily_cash_record, name="daily_cash_record"),
    path(r"cash-record-list/", v.CashRecordList.as_view(), name="cash-record-list"),
    path(r"cash-record-create/", v.CashRecordCreate.as_view(), name="cash-record-create"),
    path(r"cash-record-update/<int:pk>/", v.CashRecordUpdate.as_view(), name="cash-record-update"),
]

ffba/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_v
from django.views.generic import TemplateView

from . import views as v

urlpatterns = [
    path(r"admin/", admin.site.urls),
    # path(r"org/", include("org.urls")),
    # path(r"todo/", include("todo.urls")),
    # path(r"prod/", include("prod.urls")),
    path(r"sales/", include("sales.urls")),
    # path(r"ae/", include("ae.urls")),
    # path(r"restut/", include("restut.urls")),
    # path(r"novelty/", include("novelty.urls")),      # TODO - delete, temporary app
    # path(r"ponynote/", include("ponynote.urls")),    # TODO - delete, temporary app
    # path(r"timetr/", include("timetr.urls")),    # TODO - delete, temporary app
    # path(r"tt/", include("tt.urls")),    # TODO - delete, temporary app
    path(r"login/", auth_v.LoginView.as_view(), name="login"),
    path(r"logout/", auth_v.LogoutView.as_view(), {'next_page': reverse_lazy("home")}, name="logout"),
    path(r"password-change/?", auth_v.PasswordChangeView.as_view(), name="password-change"),
    path(r"password-change-done/?", auth_v.PasswordChangeDoneView.as_view(), name="password-change-done"),
    path(r"about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path(r"", TemplateView.as_view(template_name="home.html"), {'template_name': "home.html"}, name="home"),
    # path(r"api-auth/", include('rest_framework.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path(r"__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

prod/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views as v
from . import api


app_name = "prod"

urlpatterns = [
    path(r"product-type-list/", v.ProductTypeList.as_view(), name="product-type-list"),
    path(r"product-type-list-create-api/", api.ProductType_list_create_api.as_view(), name="product-type-list-create-api"),
    path(r"product-type-create/", v.ProductTypeCreate.as_view(), name="product-type-create"),
    path(r"product-type-update/<int:pk>/", v.ProductTypeUpdate.as_view(), name="product-type-update"),
    path(r"product-list/", v.ProductList.as_view(), name="product-list"),
    path(r"product-list-create-api/", api.Product_list_create_api.as_view(), name="product-list-create-api"),
    path(r"product-create/", v.ProductCreate.as_view(), name="product-create"),
    path(r"product-update/<int:pk>/", v.ProductUpdate.as_view(), name="product-update"),
    path(r"product-composition-list/", v.ProductCompositionList.as_view(), name="product-composition-list"),
    path(r"product-composition-list-create-api/", api.ProductComposition_list_create_api.as_view(), name="product-composition-list-create-api"),
    path(r"product-composition-create/", v.ProductCompositionCreate.as_view(), name="product-composition-create"),
    path(r"product-composition-app/", TemplateView.as_view(template_name="prod/product-composition-app.html"), name="product-composition-app"),
    # path(r"product-composition-edit/<int:pk>/", v.ProductCompositionEdit.as_view(), name="product-composition-edit"),
]

sales/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from . import reports as r
from . import api as api
from . import app as app


app_name = "sales"

urlpatterns = [
    path(r"sales-data-by-org-unit/", r.SalesDataByOrgUnit.as_view(), name="sales-data-by-org-unit"),
    path(r"totals-by-date/", r.TotalsByDate.as_view(), name="totals-by-date"),
    path(r"date-cashreg/<int:year>/<int:month>/<int:mday>/<int:cashreg_id>/", r.DaySales.as_view(), name="date-cashreg"),
    re_path("^daily-totals-for-period-api/((((?P<y_0>[0-9]{4})\.)?(?P<m_0>[0-9]{2})\.)?(?P<d_0>[0-9]{2})(-(((?P<y_1>[0-9]{4})\.)?(?P<m_1>[0-9]{2})\.)?(?P<d_1>[0-9]{2}))?)?$", api.DailyTotalsForPeriod.as_view()),
    # path("daily-totals-for-period-api/<int:y_0>.<int:m_0>.<int:d_0>", api.DailyTotalsForPeriod.as_view()),
    # path("daily-totals-for-period-api", api.DailyTotalsForPeriod.as_view()),
    path(r"", app.Sales.as_view(template_name="sales.html"), name="sales"),
]

sales/templates/sales/day_sales.html
{% extends "base_page_container.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% load misc_template_lib %}

{% block page_title %}
  Day Sales
{% endblock %}


{% block content %}
  <h1>Day Sales</h1>
  <h2>Date: {{ sales_date }}; Cashreg: {{ cashreg.identity }}</h2>

  {% if totals %}
    <h3>Totals</h3>
    <table class="table table-hover">
      <tr>
        <th>Un.</th>
        <th>Act.S.V.</th>
        <th>Exp.S.V.</th>
        <th>Dis.Los.S.V.</th>
        <th>Fr.Un.</th>
        <th>Fr.Act.S.V</th>
        <th>Fr.Exp.S.V.</th>
        <th>Fr.Los.S.V.</th>
      </tr>
      <tr>
        <td>{{ totals.units|float_format_0_2 }}</td>
        <td>{{ totals.actual_sales_value|float_format_0_2 }}</td>
        <td>{{ totals.expected_sales_value|float_format_0_2 }}</td>
        <td>{{ totals.dscn_lost_sales_value|float_format_0_2 }}</td>
        <td>{{ totals.fractional_units }}</td>
        <td>{{ totals.fractional_actual_sales_value|float_format_0_2 }}</td>
        <td>{{ totals.fractional_expected_sales_value|float_format_0_2 }}</td>
        <td>{{ totals.fractional_lost_sales_value|float_format_0_2 }}</td>
      </tr>
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}

  {% if product_day_sales %}
    <h3>Day Sales by Products</h3>
    <table class="table table-hover">
      <tr>
        <th>Product Name</th>
        <th>Un.</th>
        <th>Price</th>
        <th>Act.S.V.</th>
        <th>Exp.S.V.</th>
        <th>Los.S.V.</th>
        <th>Fr.Un.</th>
        <th>Fr.Exp.S.V.</th>
        <th>Fr.Los.S.V.</th>
        <th>Prod.#</th>
      </tr>
    {% for rec in product_day_sales %}
      <tr>
        <td>{{ rec.product_name }}</td>
        <td>{{ rec.units|float_format_0_2 }}</td>
        <td>{{ rec.product_pricesell|float_format_0_2 }}</td>
        <td>{{ rec.actual_sales_value|float_format_0_2 }}</td>
        <td>{{ rec.expected_sales_value|float_format_0_2 }}</td>
        <td>{{ rec.dscn_lost_sales_value|float_format_0_2 }}</td>
        <td>{{ rec.fractional_units|float_format_0_2 }}</td>
        <td>{{ rec.fractional_expected_sales_value|float_format_0_2 }}</td>
        <td>{{ rec.fractional_lost_sales_value|float_format_0_2 }}</td>
        <td>{{ rec.product_reference }}</td>
      </tr>
    {% endfor %}
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}

  {% if day_sales_recs %}
    <h3>Day Sales Records</h3>
    <table class="table table-hover">
      <tr>
        <th>Date</th>
        <th>Product Name</th>
        <th>Un.</th>
        <th>Price</th>
        <th>Act.S.V.</th>
        <th>Exp.S.V.</th>
        <th>Dis.%</th>
        <th>Los.S.V.</th>
        <th>Fr.Un.</th>
        {% comment %} <th>Fr.Act.S.V.</th> {% endcomment %}
        <th>Fr.Los.S.V.</th>
        <th>Prod.#</th>
      </tr>
    {% for rec in day_sales_recs %}
      <tr>
        <td>{{ rec.sales_date|time:"H:i:s" }}</td>
        <td>{{ rec.product_name }}</td>
        <td>{{ rec.units|float_format_0_2 }}</td>
        <td>{{ rec.product_pricesell|float_format_0_2 }}</td>
        <td>{{ rec.actual_sales_value|float_format_0_2 }}</td>
        <td>{{ rec.expected_sales_value|float_format_0_2 }}</td>
        <td>{{ rec.dscn_rate|float_format_0_2:"-,0" }}</td>
        <td>{{ rec.dscn_lost_sales_value|float_format_0_2 }}</td>
        <td>{{ rec.fractional_units|float_format_0_2 }}</td>
        <td>{{ rec.fractional_lost_sales_value|float_format_0_2 }}</td>
        <td>{{ rec.product_reference }}</td>
      </tr>
    {% endfor %}
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}

{% endblock %}

sales/templates/sales/product_day_sales_SAVED.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
  Product Day Sales
{% endblock %}


{% block page_content %}
  <h1>Product Day Sales</h1>
  <h2>Date: {{ sales_date }}; Cashreg: {{ cashreg.identity }}</h2>


  <!-- {% if perms.prod.product_create %}
    <p>
      <a href={% url "prod:product-create" %}><span class="fa fa-plus"></span> Create</a>
    </p>
  {% endif %} -->

  {% if product_day_sales %}
    <h3>Total Day Sales</h3>
    <table class="table">
      <tr>
        <th>Product Name</th>
        <th>Units</th>
        <th>Price</th>
        <th>Expected Value</th>
        <th>Actual Value</th>
        <th>Lost Value</th>
      </tr>
    {% for rec in product_day_sales %}
      <tr>
        <td>{{ rec.product_name }}</td>
        <td>{{ rec.units }}</td>
        <td>{{ rec.product_pricesell }}</td>
        <td>{{ rec.expected_sales_value }}</td>
        <td>{{ rec.actual_sales_value }}</td>
        <td>{{ rec.lost_sales_value }}</td>
      </tr>
    {% endfor %}
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}

  {% if product_day_sales_fractional_units %}
    <h3>Fractional Day Sales</h3>
    <table class="table">
      <tr>
        <th>Product #</th>
        <th>Product Name</th>
        <th>Units</th>
        <th>Price</th>
        <th>Actual Value</th>
      </tr>
    {% for rec in product_day_sales_fractional_units %}
      <tr>
        <td>{{ rec.product_reference }}</td>
        <td>{{ rec.product_name }}</td>
        <td>{{ rec.units }}</td>
        <td>{{ rec.product_pricesell }}</td>
        <td>{{ rec.actual_sales_value }}</td>
      </tr>
    {% endfor %}
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}

{% endblock %}

sales/templates/sales/sales.html
{% extends "base_page_container_fluid.html" %}
{% load i18n static %}

{% block page_title %}
  {% trans "Sales" %}
{% endblock %}

{% block content %}
<div id="sales-app">SAILS APP FAILED !</div>
{% endblock %}

{% block page_js %}
  <script src="/static/bundles/ffba-sales.bundle.js"></script>
{% endblock %}

sales/templates/sales/sales_data_by_org_unit.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
  Sales Data by Cash Reg
{% endblock %}


{% block page_content %}
  <h1>Sales Data by Cash Reg</h1>

  <h2>{{ test }}</h2>

  {% comment %} {% if perms.prod.product_create %}
    <p>
      <a href={% url "prod:product-create" %}><span class="fa fa-plus"></span> Create</a>
    </p>
  {% endif %}  {% endcomment %}

  {% if object_list %}
    <table class="table">
      <tr>
        <th>Cash Reg</th>
        <th>Last Repl</th>
        <th>#</th>
      </tr>
  {% for rec in object_list %}
    <tr>
      <td>{{ rec.identity }}</td>
      <td>{{ rec.last_repl_dt }}</td>
      <td>
        {% comment %} {% if perms.prod.product_update %}
          <a href={% url "prod:product-update" pk=rec.id %}>{{ rec.id }}</a>
        {% else %} {% endcomment %}
          {{ rec.id }}
        {% comment %} {% endif %} {% endcomment %}
      </td>
    </tr>
  {% endfor %}
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}
{% endblock %}

sales/templates/sales/totals_by_date.html
{% extends "base_page_container.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% load misc_template_lib %}

{% block page_title %}
  Totals by Date
{% endblock %}


{% block content %}
  <h1>Totals by Date</h1>

  {% comment %}
  {% if perms.prod.product_create %}
    <p>
      <a href={% url "prod:product-create" %}><span class="fa fa-plus"></span> Create</a>
    </p>
  {% endif %}
  {% endcomment %}

  {% if object_list %}
    <table class="table">
      <tr>
        <th>Date</th>
        {% comment %} <th>Cashreg</th> {% endcomment %}
        <th>Act.S.V.</th>
        <th>Exp.S.V.</th>
        <th>Dis.S.V.</th>
      </tr>
      {% for rec in object_list %}
        <tr>
            <td>
              <label for="{{ rec.sdate }}">{{ rec.sdate }} <span class="fa fa-angle-down ffba-angle-0"></span></label>
              <input type="checkbox" name="{{ rec.sdate }}" id="{{ rec.sdate }}" data-toggle="ffba-toggle-0" style="display: none">
            </td>
            <td>{{ rec.actual_sales_value|float_format_0_2 }}</td>
            <td>{{ rec.expected_sales_value|float_format_0_2 }}</td>
            <td>{{ rec.discount_value|float_format_0_2 }}</td>
        </tr>
        <tbody class="ffba-hide-0" style="display: none">
            {% for cr in rec.cashreg_recs %}
              <tr>
                <td>
                  {% comment %} {% if perms.sales.xxx %} {% endcomment %}
                    <a href={% url "sales:date-cashreg" cashreg_id=cr.cashreg_id year=cr.sdate.year month=cr.sdate.month mday=cr.sdate.day %}>
                      {{ cr.cashreg_identity }}
                    </a>
                  {% comment %} {% else %}
                    {{ cr.cashreg_identity }}
                  {% endif %} {% endcomment %}
                </td>
                <td>{{ cr.actual_sales_value|float_format_0_2 }}</td>
                <td>{{ cr.expected_sales_value|float_format_0_2 }}</td>
                <td>{{ cr.discount_value|float_format_0_2 }}</td>
              </tr>
            {% endfor %}
        </tbody>
      {% endfor %}
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}

{% endblock %}

{% block page_js %}

  <script>
    $(document).ready(function() {
      $('[data-toggle="ffba-toggle-0"]').change(function(){
        ffba_hide_ = $(this).parents().next(".ffba-hide-0")
        if(ffba_hide_.css("display") == "none") {
          $(this).prev().children(".ffba-angle-0").removeClass().addClass("fa fa-angle-up ffba-angle-0")
        } else {
          $(this).prev().children(".ffba-angle-0").removeClass().addClass("fa fa-angle-down ffba-angle-0")
        }
        ffba_hide_.toggle();
      });
      $('[data-toggle="ffba-toggle-1"]').change(function(){
        ffba_hide_ = $(this).parents().next(".ffba-hide-1")
        if(ffba_hide_.css("display") == "none") {
          $(this).prev().children(".ffba-angle-1").removeClass().addClass("fa fa-angle-up ffba-angle-1")
        } else {
          $(this).prev().children(".ffba-angle-1").removeClass().addClass("fa fa-angle-down ffba-angle-1")
        }
        ffba_hide_.toggle();
      });
      $('[data-toggle="ffba-toggle-2"]').change(function(){
        ffba_hide_ = $(this).parents().next(".ffba-hide-2")
        if(ffba_hide_.css("display") == "none") {
          $(this).prev().children(".ffba-angle-2").removeClass().addClass("fa fa-angle-up ffba-angle-2")
        } else {
          $(this).prev().children(".ffba-angle-2").removeClass().addClass("fa fa-angle-down ffba-angle-2")
        }
        ffba_hide_.toggle();
      });
    });
  </script>

{% endblock %}