ae/urls.py
from django.urls import path

from . import views as v


app_name = "ae"

urlpatterns = [
    # url(r"daily-cash-record/$", cash_records.daily_cash_record, name="daily_cash_record"),
    path(r"cash-record-list/", v.CashRecordList.as_view(), name="cash-record-list"),
    path(r"cash-record-create/", v.CashRecordCreate.as_view(), name="cash-record-create"),
    path(r"cash-record-update/<int:pk>/", v.CashRecordUpdate.as_view(), name="cash-record-update"),
]

ffba/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_v
from django.views.generic import TemplateView

from . import views as v

urlpatterns = [
    path(r"admin/", admin.site.urls),
    # path(r"org/", include("org.urls")),
    # path(r"todo/", include("todo.urls")),
    # path(r"prod/", include("prod.urls")),
    path(r"sales/", include("sales.urls")),
    # path(r"ae/", include("ae.urls")),
    # path(r"restut/", include("restut.urls")),
    # path(r"novelty/", include("novelty.urls")),      # TODO - delete, temporary app
    # path(r"ponynote/", include("ponynote.urls")),    # TODO - delete, temporary app
    # path(r"timetr/", include("timetr.urls")),    # TODO - delete, temporary app
    # path(r"tt/", include("tt.urls")),    # TODO - delete, temporary app
    path(r"login/", auth_v.LoginView.as_view(), name="login"),
    path(r"logout/", auth_v.LogoutView.as_view(), {'next_page': reverse_lazy("home")}, name="logout"),
    path(r"password-change/?", auth_v.PasswordChangeView.as_view(), name="password-change"),
    path(r"password-change-done/?", auth_v.PasswordChangeDoneView.as_view(), name="password-change-done"),
    path(r"about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path(r"", TemplateView.as_view(template_name="home.html"), {'template_name': "home.html"}, name="home"),
    # path(r"api-auth/", include('rest_framework.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path(r"__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

ae/models.py
from django.db import models

from misc import models as misc
from org import models as org


class CashRegister(misc.AuditMixin, misc.Root):
    name = models.CharField(max_length=200)
    org_unit = models.ForeignKey(org.OrgUnit, on_delete=models.PROTECT, related_name="cash_registers")
    show_order = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "ffba_cash_register"
        unique_together = ('name', 'org_unit')
        ordering = ['show_order']


class CashRecord(misc.RecordDateMixin, misc.AuditMixin, misc.Root):
    cash_register = models.ForeignKey(CashRegister, on_delete=models.PROTECT, unique_for_date="record_date", related_name="cash_records")
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    checks = models.IntegerField(null=True, blank=True)
    url = models.URLField(max_length=1000, null=True, blank=True)


#	def save(self, *args, **kwargs):
#		# Check how the current values differ from ._loaded_values. For example,
#		# prevent changing the creator_id of the model. (This example doesn't
#		# support cases where 'creator_id' is deferred).
#		#if not self._state.adding and (
#		#		self.creator_id != self._loaded_values['creator_id']):
#		#	raise ValueError("Updating the value of creator isn't allowed")
#		self.created_by = etc_models.Root.thread.request.user
#		#print("created_by_id=%s" % etc_models.Root.thread.request.user.id)
#		super(CashRecord, self).save(*args, **kwargs)

    #def __str__(self):
    #	return unicode(self.record_date)

    class Meta:
        db_table = "ffba_cash_record"
        ordering = ['record_date', 'cash_register']

        permissions = (
            ("cash_record_create", "cashrecord / create"),
            ("cash_record_create_any", "cashrecord / createany"),
            ("cash_record_update", "cashrecord / update"),
            ("cash_record_update_any", "cashrecord / updateany"),
            ("cash_record_list", "cashrecord / list"),
            ("cash_record_list_all", "cashrecord / listall"),
        )


#class Expense(etc_models.RecDateTimeMixin, etc_models.RootAu):
#
#	UNDEFINED = 'UNDEF'
#	PRODUCT_PURCHASE = 'PROD_PURCHASE'
#
#	EXPENSE_TYPE_CHOICES = (
#		(UNDEFINED, "Undefined"),
#		(PRODUCT_PURCHASE, "Product Purchase"),
#	)
#
#	type = models.CharField(max_length=30, choices=EXPENSE_TYPE_CHOICES, default=UNDEFINED)
#	unit_price = models.DecimalField(max_digits=15, decimal_places=5, null=True, blank=True)
#	units = models.IntegerField(null=True, blank=True)
#	amount = models.DecimalField(max_digits=15, decimal_places=5)
#
#	def save(self, *args, **kwargs):
#
#		if self.amount is None and self.unit_price and self.units:
#			self.amount = self.unit_price * self.units
#
#		super(Expense, self).save(*args, **kwargs)
#
#	def __str__(self):
#		return self.type + "; unitprice=" + str(self.unit_price) + "; units=" + str(self.units) + "; amount=" + #str(self.amount)
#
#	class Meta:
#		db_table = "ffba_expense"

ae/forms.py
from django import forms
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from . import models
from misc import models as misc
#from etc import forms as etc_forms


class CashRecordForm(forms.ModelForm):

    def clean_record_date(self):
        record_date = self.cleaned_data['record_date']
        user = misc.Root.thread.request.user
        if not user.has_perm("acc.cash_record_create_any"):
            date_diff = (record_date-timezone.now().date()).days
            if date_diff > 0:
                self._errors["record_date"] = [_("Cash record in the future is not permitted")]
            if date_diff < -7:
                self._errors["record_date"] = [_("Cash record older than 7 days is not permitted")]
        return record_date

    #def get_queryset(self):
    #	return super(CashRecordForm, self).get_queryset().select_related('cash_register')

    class Meta:
        model = models.CashRecord
        fields = ["cash_register", "record_date", "amount", "checks"]
        # widgets = {
        #     "cash_register": forms.Select(attrs={"class": "form-control"}),
        #     "record_date": forms.DateInput(attrs={"class": "form-control"}),
        #     "amount": forms.NumberInput(attrs={"class": "form-control"}),
        #     "checks": forms.NumberInput(attrs={"class": "form-control"}),
        #     # "url": forms.URLInput(attrs={"class": "form-control"}),
        # }
        help_texts = {
            "cash_register": _("Money receiving terminal"),
            "record_date": _("Reporting Date"),
            "amount": _("Total sales per day"),
            "checks": _("Number of checks per day"),
        }

ae/views.py
import datetime
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy

from . import models as m
from . import forms as f


class CashRecordList(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = ("ae.cash_record_list")
    template_name = "ae/cash_record_list.html"
    context_object_name = "cash_records"

    def get_queryset(self):
        # list = m.CashRecord.objects.order_by("-record_date")
        l_ = m.CashRecord.objects.prefetch_related("cash_register", "create_user", "modify_user").order_by("-record_date", "cash_register__org_unit", "cash_register__show_order")
        if not self.request.user.has_perm("ae.cash_record_list_all"):
            l_ = l_.exclude(record_date__lt=(timezone.now()-datetime.timedelta(days=7))).filter(create_user=self.request.user)
        return l_


class CashRecordCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.edit.CreateView):
    permission_required = ("ae.cash_record_create")
    form_class = f.CashRecordForm
    template_name = "ae/cash_record.html"
    success_url = reverse_lazy("ae:cash-record-list")

    def form_valid(self, form):
        form.instance.create_user = self.request.user
        return super(CashRecordCreate, self).form_valid(form)


class CashRecordUpdate(LoginRequiredMixin, generic.edit.UpdateView):
    permission_required = ("ae.cash_record_update")
    model = m.CashRecord
    form_class = f.CashRecordForm
    template_name = "ae/cash_record.html"
    success_url = reverse_lazy("ae:cash-record-list")

ae/templates/ae/cash_record.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
  Cash per Day
{% endblock %}


{% block page_content %}
  <h1>Cash per Day</h1>

  <form method="post">{% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <span class="help-inline text-danger">{{ error }}</span>
        {% endfor %}
        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <div class="form-group">
      <button type="success" class="btn btn-outline-success"><span class="fa fa-check"></span> Submit</button>
      <a href="{% url 'ae:cash-record-list' %}" class="btn btn-outline-secondary"><span class="fa fa-times"></span> Cancel (abandon changes)</a>
    </div>

  </form>

{% endblock %}

ae/templates/ae/cash_record_list.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block page_title %}
  Cash Record List
{% endblock %}


{% block page_content %}
  <h1>Cash Record List</h1>

  {% if perms.ae.cash_record_create %}
    <p>
      <a href={% url "ae:cash-record-create" %}><span class="fa fa-plus"></span> Create</a>
    </p>
  {% endif %}

  {% if object_list %}
    <table class="table">
      <tr>
        <th>Cash Reg.</th>
        <th>Date</th>
        <th>Amount</th>
        <th>Checks</th>
        {% comment %} <th>URL</th> {% endcomment %}
        <th>Created By</th>
        <th>#</th>
      </tr>
      {% for rec in object_list %}
        <tr>
          <td>{{ rec.cash_register.name }}</td>
          <td>{{ rec.record_date|date:"d.m.Y" }}</td>
          <td>{{ rec.amount|floatformat:"2" }}</td>
          <td>{{ rec.checks }}</td>
          {% comment %} <td>{% if rec.url %}<a href={{ rec.url }}>@url</a>{% endif %}</td> {% endcomment %}
          <td>{{ rec.create_user }}</td>
          <td>
              {% if perms.ae.cash_record_update %}
                <a href={% url "ae:cash-record-update" pk=rec.id %}>{{ rec.id }}</a>
              {% else %}
                {{ rec.id }}
              {% endif %}
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}
{% endblock %}