ae/urls.py
from django.urls import path

from . import views as v


app_name = "ae"

urlpatterns = [
    # url(r"daily-cash-record/$", cash_records.daily_cash_record, name="daily_cash_record"),
    path(r"cash-record-list/", v.CashRecordList.as_view(), name="cash-record-list"),
    path(r"cash-record-create/", v.CashRecordCreate.as_view(), name="cash-record-create"),
    path(r"cash-record-update/<int:pk>/", v.CashRecordUpdate.as_view(), name="cash-record-update"),
]

ffba/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_v
from django.views.generic import TemplateView

from . import views as v

urlpatterns = [
    path(r"admin/", admin.site.urls),
    # path(r"org/", include("org.urls")),
    # path(r"todo/", include("todo.urls")),
    # path(r"prod/", include("prod.urls")),
    path(r"sales/", include("sales.urls")),
    # path(r"ae/", include("ae.urls")),
    # path(r"restut/", include("restut.urls")),
    # path(r"novelty/", include("novelty.urls")),      # TODO - delete, temporary app
    # path(r"ponynote/", include("ponynote.urls")),    # TODO - delete, temporary app
    # path(r"timetr/", include("timetr.urls")),    # TODO - delete, temporary app
    # path(r"tt/", include("tt.urls")),    # TODO - delete, temporary app
    path(r"login/", auth_v.LoginView.as_view(), name="login"),
    path(r"logout/", auth_v.LogoutView.as_view(), {'next_page': reverse_lazy("home")}, name="logout"),
    path(r"password-change/?", auth_v.PasswordChangeView.as_view(), name="password-change"),
    path(r"password-change-done/?", auth_v.PasswordChangeDoneView.as_view(), name="password-change-done"),
    path(r"about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path(r"", TemplateView.as_view(template_name="home.html"), {'template_name': "home.html"}, name="home"),
    # path(r"api-auth/", include('rest_framework.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path(r"__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

prod/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views as v
from . import api


app_name = "prod"

urlpatterns = [
    path(r"product-type-list/", v.ProductTypeList.as_view(), name="product-type-list"),
    path(r"product-type-list-create-api/", api.ProductType_list_create_api.as_view(), name="product-type-list-create-api"),
    path(r"product-type-create/", v.ProductTypeCreate.as_view(), name="product-type-create"),
    path(r"product-type-update/<int:pk>/", v.ProductTypeUpdate.as_view(), name="product-type-update"),
    path(r"product-list/", v.ProductList.as_view(), name="product-list"),
    path(r"product-list-create-api/", api.Product_list_create_api.as_view(), name="product-list-create-api"),
    path(r"product-create/", v.ProductCreate.as_view(), name="product-create"),
    path(r"product-update/<int:pk>/", v.ProductUpdate.as_view(), name="product-update"),
    path(r"product-composition-list/", v.ProductCompositionList.as_view(), name="product-composition-list"),
    path(r"product-composition-list-create-api/", api.ProductComposition_list_create_api.as_view(), name="product-composition-list-create-api"),
    path(r"product-composition-create/", v.ProductCompositionCreate.as_view(), name="product-composition-create"),
    path(r"product-composition-app/", TemplateView.as_view(template_name="prod/product-composition-app.html"), name="product-composition-app"),
    # path(r"product-composition-edit/<int:pk>/", v.ProductCompositionEdit.as_view(), name="product-composition-edit"),
]

sales/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from . import reports as r
from . import api as api
from . import app as app


app_name = "sales"

urlpatterns = [
    path(r"sales-data-by-org-unit/", r.SalesDataByOrgUnit.as_view(), name="sales-data-by-org-unit"),
    path(r"totals-by-date/", r.TotalsByDate.as_view(), name="totals-by-date"),
    path(r"date-cashreg/<int:year>/<int:month>/<int:mday>/<int:cashreg_id>/", r.DaySales.as_view(), name="date-cashreg"),
    re_path("^daily-totals-for-period-api/((((?P<y_0>[0-9]{4})\.)?(?P<m_0>[0-9]{2})\.)?(?P<d_0>[0-9]{2})(-(((?P<y_1>[0-9]{4})\.)?(?P<m_1>[0-9]{2})\.)?(?P<d_1>[0-9]{2}))?)?$", api.DailyTotalsForPeriod.as_view()),
    # path("daily-totals-for-period-api/<int:y_0>.<int:m_0>.<int:d_0>", api.DailyTotalsForPeriod.as_view()),
    # path("daily-totals-for-period-api", api.DailyTotalsForPeriod.as_view()),
    path(r"", app.Sales.as_view(template_name="sales.html"), name="sales"),
]

ffba/views.py
from django.views import View
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin


class CBV_example(View):
    template_name = "template.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

ffba/templates/about.html
{% extends "base_site.html" %}
{% load i18n static %}

{# EMPTY extrastyle #}{% block extrastyle %}{% endblock %}
{# EMPTY usertools #}{% block usertools %}{% endblock %}
{# EMPTY content_title #}{% block content_title %}{% endblock %}
{# EMPTY breadcrumbs #}{% block breadcrumbs %}{% endblock %}

{% block content %}
{% blocktrans %}
About Food Factory Business Automation (FFBA)
{% endblocktrans %} {# blocktrans #}
{% endblock %} {# content #}

ffba/templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

{# SITE_TITLE | page_title #}
<title>{% block site_title %}SITE_TITLE{% endblock %} / {% block page_title %}Page Title{% endblock %}</title>

{% block site_styles %}
  {% block bootstrap_styles %}
    <link rel="stylesheet" href={% static "css/bootstrap.css" %}>
  {% endblock %}
  {% block page_styles %}{% endblock %}
  {% block fontawesome_styles %}
    <link rel="stylesheet" href={% static "css/fontawesome-all.css" %}>
  {% endblock %}
{% endblock %}

{% if LANGUAGE_BIDI %}
  <link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "css/rtl.css" %}{% endblock %}" />
{% endif %}

{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}

</head>
<body>

{% load i18n %}
{% block header %}{% endblock %}
{% block body_content %}{% endblock %}

{% block js %}
  {% block jquery_js %}
    <script src={% static "js/jquery-3.3.1.js" %}></script>
  {% endblock %}
  {% block popper_js %}
    <script src={% static "js/popper.js" %}></script>
  {% endblock %}
  {% block bootstrap_js %}
    <script src={% static "js/bootstrap.bundle.js" %}></script>
  {% endblock %}
  {% block site_js %}{% endblock %}
{% endblock %}

{% block page_bottom_ext %} {% endblock %}

</body>
</html>

ffba/templates/base_page_blank.html
{% extends "base_site.html" %}
{% load i18n static %}

ffba/templates/base_page_container.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block page_content %}
<div class="container">
  {% block content %}{% endblock %}
</div>
{% endblock %}

ffba/templates/base_page_container_fluid.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block page_content %}
<div class="container-fluid">
    {% block content %}{% endblock %}
  </div>
{% endblock %}

ffba/templates/base_page_ext.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block page_content %}
<div class="container-fluid">
  <div id="todo-app"></div>
</div>
{% endblock %}

{% block page_bottom_ext %}

  <script>
    $(document).ready(function() {
      $('[data-toggle="ffba-toggle-0"]').change(function(){
        ffba_hide_ = $(this).parents().next(".ffba-hide-0")
        if(ffba_hide_.css("display") == "none") {
          $(this).prev().children(".ffba-angle-0").removeClass().addClass("fa fa-angle-up ffba-angle-0")
        } else {
          $(this).prev().children(".ffba-angle-0").removeClass().addClass("fa fa-angle-down ffba-angle-0")
        }
        ffba_hide_.toggle();
      });
      $('[data-toggle="ffba-toggle-1"]').change(function(){
        ffba_hide_ = $(this).parents().next(".ffba-hide-1")
        if(ffba_hide_.css("display") == "none") {
          $(this).prev().children(".ffba-angle-1").removeClass().addClass("fa fa-angle-up ffba-angle-1")
        } else {
          $(this).prev().children(".ffba-angle-1").removeClass().addClass("fa fa-angle-down ffba-angle-1")
        }
        ffba_hide_.toggle();
      });
      $('[data-toggle="ffba-toggle-2"]').change(function(){
        ffba_hide_ = $(this).parents().next(".ffba-hide-2")
        if(ffba_hide_.css("display") == "none") {
          $(this).prev().children(".ffba-angle-2").removeClass().addClass("fa fa-angle-up ffba-angle-2")
        } else {
          $(this).prev().children(".ffba-angle-2").removeClass().addClass("fa fa-angle-down ffba-angle-2")
        }
        ffba_hide_.toggle();
      });
    });
  </script>

{% endblock %}

ffba/templates/base_site.html
{% extends "base.html" %}
{% load i18n static %}

{% block site_title %}
  ELTA
{% endblock %}

{% block header %}
<header>
  <nav class="navbar navbar-expand-md navbar-light bg-light rounded">

    <a class="navbar-brand" href="{% url 'home' %}" aria-label="ELTA">{% trans "ELTA" %}</a>

    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label={% trans "Toggle navigation" %}>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTop">

      <ul class="navbar-nav mr-auto">

        {% comment %}
        <li class="nav-item active">
          <a class="nav-link" href="#">Dummy <span class="sr-only">(current)</span></a>
        </li>
        {% endcomment %}

        {# MENU Sales #}
        {% if perms.sales %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="sales_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Sales" %}</a>
            <div class="dropdown-menu" aria-labelledby="sales_dropdown">

              {# {% if perms.prod.product_list %} #}
              <a class="dropdown-item" href="{% url 'sales:sales' %}">{% trans "Sales New" %}</a>
              {# {% endif %} #}

              {# {% if perms.prod.product_list %} #}
                <a class="dropdown-item" href="{% url 'sales:totals-by-date' %}">{% trans "Totals by Date (old)" %}</a>
              {# {% endif %} #}

              {% comment %}
              {% if perms.prod.product_type_list %}
                <a class="dropdown-item" href="{% url 'prod:product-type-list' %}">{% trans "Product Types" %}</a>
              {% endif %}
              {% endcomment %}

            </div>
          </li>
        {% endif %}

        {# MENU Products #}
        {% comment %}
        {% if perms.prod %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="prod_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Products" %}</a>
            <div class="dropdown-menu" aria-labelledby="prod_dropdown">

              {% if perms.prod.product_list %}
                <a class="dropdown-item" href="{% url 'prod:product-list' %}">{% trans "Products" %}</a>
              {% endif %}

              {% if perms.prod.product_type_list %}
                <a class="dropdown-item" href="{% url 'prod:product-type-list' %}">{% trans "Product Types" %}</a>
              {% endif %}

            </div>
          </li>
        {% endif %}
        {% endcomment %}

        {# MENU AE #}
        {% comment %}
        {% if perms.ae %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="ae_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "AE" %}</a>
            <div class="dropdown-menu" aria-labelledby="ae_dropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              {% if perms.ae.cash_record_list %}
                <a class="dropdown-item" href="{% url 'ae:cash-record-list' %}">{% trans "Daily Cash" %}</a>
              {% endif %}
            </div>
          </li>
        {% endif %}
        {% endcomment %}


      </ul> {# top menu #}

      {% comment %}
      TODO +search engine on site level
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder={% trans "Search" %} aria-label={% trans "Search" %}>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
      </form>
      {% endcomment %}

      {% if user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="settingsTop" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              {% if user.first_name or user.last_name %}
                {{user.first_name}} {{user.last_name}}
              {% else %}
                {{ user.username }}
              {% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right text-right" aria-labelledby="settingsTop">
              <a class="dropdown-item" href="#">{% trans "Password Change" %}</a>
              {% comment %} <a href="{% url 'password-change' %}">{% trans "Password Change" %}</a> {% endcomment %}
              {% comment %} <li role="separator" class="divider"></li> {% endcomment %}
              <a class="dropdown-item" href="{% url 'logout' %}">{% trans "Logout" %}</a>
              {% comment %} <li role="separator" class="divider"></li> {% endcomment %}
              <a class="dropdown-item" href="{% url 'about' %}">{% trans "About" %}</a>
              {% comment %} <li><a href="{% url 'about' %}">{% trans "About" %}</a></li> {% endcomment %}
            </div>
          </li>
        </ul>
      {% else %}
        <a class="nav-link" href="{% url 'login' %}">{% trans "Login" %} <span class="sr-only">(current)</span></a>
      {% endif %}

    </div>
  </nav>
</header>
{% endblock %}

{% comment %}
{% block navbar %}
  {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
      <a class="navbar-brand" href="{% url 'home' %}">{% trans "ELTA" %}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label={% trans "Toggle navigation" %}>
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTop">
        <ul class="navbar-nav mr-auto">

          {# MENU Products #}
          {% if perms.prod %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="prod_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Products" %}</a>
              <div class="dropdown-menu" aria-labelledby="prod_dropdown">

                {% if perms.prod.product_list %}
                  <a class="dropdown-item" href="{% url 'prod:product-list' %}">{% trans "Products" %}</a>
                {% endif %}

                {% if perms.prod.product_type_list %}
                  <a class="dropdown-item" href="{% url 'prod:product-type-list' %}">{% trans "Product Types" %}</a>
                {% endif %}

              </div>
            </li>
          {% endif %}

          {# MENU AE #}
          {% if perms.ae %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="ae_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "AE" %}</a>
              <div class="dropdown-menu" aria-labelledby="ae_dropdown">
                {% if perms.ae.cash_record_list %}
                  <a class="dropdown-item" href="{% url 'ae:cash-record-list' %}">{% trans "Daily Cash" %}</a>
                {% endif %}
              </div>
            </li>
          {% endif %}
        </ul>

        <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="settingsTop" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                {% if user.first_name or user.last_name %}
                  {{user.first_name}} {{user.last_name}}
                {% else %}
                  {{ user.username }}
                {% endif %}
              </a>
              <div class="dropdown-menu dropdown-menu-right text-right" aria-labelledby="settingsTop">
                <a class="dropdown-item" href="#">{% trans "Password Change" %}</a>
                <a class="dropdown-item" href="{% url 'logout' %}">{% trans "Logout" %}</a>
                <a class="dropdown-item" href="{% url 'about' %}">{% trans "About" %}</a>
              </div>
            </li>
          </ul>
        </div>
    </nav>
  {% endif %}
{% endblock %}
{% endcomment %}

{% block body_content %}
  {% block page_content %}
  {% endblock %}
{% endblock %}

{% block site_js %}
  {% block page_js %}{% endblock %}
{% endblock %}

ffba/templates/home.html
{% extends "base_page_blank.html" %}
{% load i18n static %}

{% block page_title %}
  {% trans "Home" %}
{% endblock %}