ae/urls.py
from django.urls import path

from . import views as v


app_name = "ae"

urlpatterns = [
    # url(r"daily-cash-record/$", cash_records.daily_cash_record, name="daily_cash_record"),
    path(r"cash-record-list/", v.CashRecordList.as_view(), name="cash-record-list"),
    path(r"cash-record-create/", v.CashRecordCreate.as_view(), name="cash-record-create"),
    path(r"cash-record-update/<int:pk>/", v.CashRecordUpdate.as_view(), name="cash-record-update"),
]

ffba/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_v
from django.views.generic import TemplateView

from . import views as v

urlpatterns = [
    path(r"admin/", admin.site.urls),
    # path(r"org/", include("org.urls")),
    # path(r"todo/", include("todo.urls")),
    # path(r"prod/", include("prod.urls")),
    path(r"sales/", include("sales.urls")),
    # path(r"ae/", include("ae.urls")),
    # path(r"restut/", include("restut.urls")),
    # path(r"novelty/", include("novelty.urls")),      # TODO - delete, temporary app
    # path(r"ponynote/", include("ponynote.urls")),    # TODO - delete, temporary app
    # path(r"timetr/", include("timetr.urls")),    # TODO - delete, temporary app
    # path(r"tt/", include("tt.urls")),    # TODO - delete, temporary app
    path(r"login/", auth_v.LoginView.as_view(), name="login"),
    path(r"logout/", auth_v.LogoutView.as_view(), {'next_page': reverse_lazy("home")}, name="logout"),
    path(r"password-change/?", auth_v.PasswordChangeView.as_view(), name="password-change"),
    path(r"password-change-done/?", auth_v.PasswordChangeDoneView.as_view(), name="password-change-done"),
    path(r"about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path(r"", TemplateView.as_view(template_name="home.html"), {'template_name': "home.html"}, name="home"),
    # path(r"api-auth/", include('rest_framework.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path(r"__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

prod/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views as v
from . import api


app_name = "prod"

urlpatterns = [
    path(r"product-type-list/", v.ProductTypeList.as_view(), name="product-type-list"),
    path(r"product-type-list-create-api/", api.ProductType_list_create_api.as_view(), name="product-type-list-create-api"),
    path(r"product-type-create/", v.ProductTypeCreate.as_view(), name="product-type-create"),
    path(r"product-type-update/<int:pk>/", v.ProductTypeUpdate.as_view(), name="product-type-update"),
    path(r"product-list/", v.ProductList.as_view(), name="product-list"),
    path(r"product-list-create-api/", api.Product_list_create_api.as_view(), name="product-list-create-api"),
    path(r"product-create/", v.ProductCreate.as_view(), name="product-create"),
    path(r"product-update/<int:pk>/", v.ProductUpdate.as_view(), name="product-update"),
    path(r"product-composition-list/", v.ProductCompositionList.as_view(), name="product-composition-list"),
    path(r"product-composition-list-create-api/", api.ProductComposition_list_create_api.as_view(), name="product-composition-list-create-api"),
    path(r"product-composition-create/", v.ProductCompositionCreate.as_view(), name="product-composition-create"),
    path(r"product-composition-app/", TemplateView.as_view(template_name="prod/product-composition-app.html"), name="product-composition-app"),
    # path(r"product-composition-edit/<int:pk>/", v.ProductCompositionEdit.as_view(), name="product-composition-edit"),
]

prod/models.py
from django.db import models
from django.urls import reverse_lazy
# from mptt.models import MPTTModel, TreeForeignKey

from misc import models as m


class ProductType(m.AuditMixin, m.Root):
    code = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=1000, unique=True)
    show_order = models.CharField(max_length=100, null=True, blank=True)

    def get_absolute_url(self):
        return reverse_lazy("prod:product-type-list")

    def __str__(self):
        return "%s (%s)" % (self.name, self.code)

    class Meta:
        db_table = "ffba_product_type"


class Product(m.AuditMixin, m.Root):
    code = models.CharField(max_length=50, unique=True, null=True, blank=True)
    product_type = models.ForeignKey(ProductType, on_delete=models.PROTECT, to_field="code", db_column="product_type_code")
    name = models.CharField(max_length=1000)
    # note = models.CharField(max_length=5000, null=True, blank=True)

    def get_absolute_url(self):
        return reverse_lazy("prod:product-list")

    def get_code(self):
        return self.code and self.code or "ID_%s" % (self.id)

    def __str__(self):
        return "%s" % (self.name, )

    class Meta:
        db_table = "ffba_product"


class ProductComposition(m.AuditMixin, m.Root):
    up = models.ForeignKey(Product, on_delete=models.CASCADE, to_field="code", db_column="up_code", related_name="composition")
    product = models.ForeignKey(Product, on_delete=models.PROTECT, to_field="code", db_column="product_code", related_name="product")
    note = models.CharField(max_length=5000, null=True, blank=True)
    weight_initial = models.DecimalField(max_digits=11, decimal_places=5, null=True, blank=True)
    # weight_final = models.DecimalField(max_digits=11, decimal_places=5, null=True, blank=True)
    # weight_reduction = models.DecimalField(max_digits=6, decimal_places=4, null=True, blank=True)
    # weight_initial_per_gram = models.DecimalField(max_digits=11, decimal_places=5, null=True, blank=True)
    # weight_final_per_gram = models.DecimalField(max_digits=11, decimal_places=5, null=True, blank=True)

    def get_absolute_url(self):
        return reverse_lazy("prod:product-composition-list")

    class Meta:
        db_table = "ffba_product_composition"
        unique_together = (("up", "product"), )


#
#	#def get_absolute_url(self):
#	#	return reverse_lazy("prod:product-link")

	# def __str__(self):
	# 	return " ".join([self.up.name, " >-- ", self.entry.name])


# class ProductPurchase(m.Root):
#	expense = models.OneToOneField(acc_models.Expense, on_delete=models.PROTECT, related_name="product_purchase")
#	product = models.ForeignKey(Product, related_name="products_purchases", null=True, blank=True)
#	product_text = models.CharField(max_length=500, null=True, blank=True)
#	#+ provider
#	provider_text = models.CharField(max_length=500, null=True, blank=True)
#
#	history = HistoricalRecords(table_name="ffba_product_purchase_history")
#
#	def get_absolute_url(self):
#		return reverse_lazy("prod:product-purchase-list")
#
#	#def __str__(self):
#		#return self.name
#
#	class Meta:
#		db_table = "ffba_product_purchase"

prod/forms.py
from django.forms import ModelForm
from django.forms import inlineformset_factory

from . import models as m


class ProductCompositionForm(ModelForm):

    class Meta:
        model = m.ProductComposition
        fields = ["product", "weight_initial", "note"]


ProductCompositionFormSet = inlineformset_factory(m.Product, m.ProductComposition, form=ProductCompositionForm, fk_name="up")


# class ProductForm(ModelForm):

#     class Meta:
#         model = m.Product
#         fields = ["code", "product_type", "name", "desc"]

prod/views.py
from django.views.generic import ListView, CreateView, UpdateView
# from django.views.generic.edit import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# from django.urls import reverse_lazy

# from misc.edit import MasterDetailEditView
# from . import forms as f
from . import models as m


class ProductTypeList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = ("prod.product_type_list")
    model = m.ProductType
    template_name = "prod/product_type_list.html"

    def get_queryset(self):
        return m.ProductType.objects.order_by("show_order")


class ProductTypeCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ("prod.product_type_create")
    model = m.ProductType
    fields = ["code", "name", "show_order"]
    template_name = "prod/product_type.html"


class ProductTypeUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ("prod.product_type_update")
    model = m.ProductType
    fields = ["code", "name", "show_order"]
    template_name = "prod/product_type.html"


class ProductList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = ("prod.product_list")
    model = m.Product
    template_name = "prod/product_list.html"

    def get_queryset(self):
        return m.Product.objects.prefetch_related("product_type").order_by("name")


class ProductCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ("prod.product_create")
    model = m.Product
    fields = ["name", "product_type", "code"]
    template_name = "prod/product.html"


class ProductUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ("prod.product_update")
    model = m.Product
    fields = ["name", "product_type", "code"]
    template_name = "prod/product.html"


class ProductCompositionList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = ("prod.product_composition_list")
    model = m.ProductComposition
    template_name = "prod/product_composition_list.html"

    # def get_queryset(self):
    #     return m.ProductComposition.objects.order_by("show_order")


class ProductCompositionCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ("prod.product_composition_create")
    model = m.ProductComposition
    fields = ["up", "product", "note", "weight_initial"]
    template_name = "prod/product_composition.html"


# class ProductCompositionEdit(LoginRequiredMixin, PermissionRequiredMixin, MasterDetailEditView):
#     permission_required = ("prod.product_composition_list")
#     model = m.Product
#     fields = ["name", "note", "product_type", "code"]
#     detail_formset_class = f.ProductCompositionFormSet
#     detail_queryset = m.ProductComposition.objects.filter(up__exact=27)
#     template_name = "prod/product_composition_edit.html"
#     success_url = reverse_lazy("prod:product-composition-edit")
#     product_composition = None

#     def get_success_url(self):
#         url_ = super(ProductCompositionEdit, self).get_success_url()
#         if self.object:
#             url_ += str(self.object.pk)
#         return url_




    # def get_context_data(self, **kwargs):
    #     context_ = super(ProductCompositionEdit, self).get_context_data(**kwargs)
    #     if self.product_composition:
    #         context_["product_composition"] = self.product_composition
    #     return context_

    # def get(self, request, *args, **kwargs):
    #     response_ = super().get(request, *args, **kwargs)
    #     self.product_composition = f.ProductCompositionFormSet()
    #     return response_

    # def post(self, request, *args, **kwargs):
    #     self.product_composition = f.ProductCompositionFormSet(queryset=m.ProductComposition.objects.filter(composition__exact='O'))
    #     return super(ProductCompositionEdit, self).get(request, *args, **kwargs)


    # def form_valid(self, form):

    #     self.object = form.save()

    #     return super(ProductCompositionEdit, self).form_valid(form)

    # def get(self, request, *args, **kwargs):
    #     return HttpResponse("Hello, World!")


# class ProductCompositionEdit(EditView):
#     # class ProductCompositionUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
#     #	permission_required = ("prod.product_composition_update")
#     model = m.ProductComposition
#     fields = ["product", "name", "note", "weight_initial", "weight_final"]

# template_name = "prod/product_composition_edit.html"


#	formset = None
#
#	def get_object(self, queryset=None):
#		obj_ = super(ProductCompositionUpdate, self).get_object(queryset)
#		print("".join(["X: get_object-01: obj=", str(obj_)]))
#
#		self.formset = f.ProductRelFormSet(instance=obj_)
#		print("".join(["X: get_object-02: formset=", str(self.formset)]))
#
#		return obj_
#
#	def get_context_data(self, **kwargs):
#		ctx_ = super(ProductCompositionUpdate, self).get_context_data(**kwargs)
#		ctx_["formset"] = self.formset
#		return ctx_

#	def get_form_kwargs(self):
#		print("".join(["X: get_form_kwargs-01: self=", str(self)]))
#		kwargs_ = super(ProductCompositionUpdate, self).get_form_kwargs()
#		kwargs_.update(self.kwargs)
#		print("".join(["X: get_form_kwargs-02: kwargs=", str(kwargs_)]))
#		return kwargs_



# class ProductCompositionUpdate(FormView):
#	form_class = inlineformset_factory(m.Product, m.ProductRelation, fk_name="up", extra=1, fields=["link"])
#	template_name = "product_compositon_update"
#
#	def form_valid(self, formset):
#		cnt_ = len(formset.save())
#		if cnt_ == 0:
#			messages.success(self.request, "%s compositions have been updated" % cnt_)
#
#		return redirect("#", self.up_id)
#
#	def get_context_data(self, **kwargs):
#		print(" ".join(["X: get_context_data-01:", "self=", str(self), "kwargs=", str(**kwargs)]))
#		ctx_ = super(ProductCompositionUpdate, self).get_context_data(**kwargs)
#		print(" ".join(["X: get_context_data-02:", "ctx=", str(ctx_)]))
#		ctx_ = ctx_.update({"col3":"Delete?"})
#		return ctx_
#
#	def get_form_kwargs(self):
#		print(" ".join(["X: get_form_kwargs-01:", "self=", str(self)]))
#		self.up_id = self.kwargs["up_id"]
#		self.up = get_object_or_404(Product, pk=self.up_id)
#		kwargs_ = super(ProductCompositionUpdate, self).get_form_kwargs()
#		kwargs_.update({"instance":self.up})
#		return kwargs_



# class ProductPurchaseList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
#	permission_required = ("prod.product_purchase_list")
#	model = m.ProductPurchase
#
#
# class ProductPurchaseCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
#	permission_required = ("prod.product_purchase_create")
#	template_name = "prod/productpurchase_form.html"
#	form_class = forms.ProductPurchaseMultiForm
#	success_url = reverse_lazy("home")
#
#	def form_valid(self, form):
#		expense = form["expense"].save()
#		product_purchase = form["product_purchase"].save(commit=False)
#		product_purchase.expense = expense
#		product_purchase.save()
#		return redirect(self.get_success_url())

prod/templates/prod/product-composition-app.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
    Product Composition
{% endblock %}

{% block page_content %}

    <h1>Product Composition</h1>

    <div id="product-composition-app"></div>
    <script src="/static/js/ffba_product_composition.bundle.js"></script>

{% endblock %}

prod/templates/prod/product.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
  Product Composition
{% endblock %}


{% block page_content %}
  <h1>Product Composition</h1>

  <form method="post">{% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    <h2>Product</h2>

    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <span class="help-inline text-danger">{{ error }}</span>
        {% endfor %}
        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}

    <div class="form-group">
      <button type="success" class="btn btn-outline-success"><span class="fa fa-check"></span> Submit</button>
      <a href="{% url 'prod:product-list' %}" class="btn btn-outline-secondary"><span class="fa fa-times"></span> Cancel (abandon changes)</a>
    </div>

  </form>

{% endblock %}

prod/templates/prod/product_composition_edit.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
  Product Composition
{% endblock %}


{% block page_content %}
  <h1>Product Composition</h1>

  <form method="post">{% csrf_token %}

    <h2>Product</h2>

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <span class="help-inline text-danger">{{ error }}</span>
        {% endfor %}
        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}

    <h2>Composition</h2>

    {% if detail_formset %}
      {{ detail_formset.management_form }}
      {{ detail_formset }}
    {% endif %}

    <div class="form-group">
      <button type="success" class="btn btn-outline-success"><span class="fa fa-check"></span> Submit</button>
      <a href="{% url 'prod:product-list' %}" class="btn btn-outline-secondary"><span class="fa fa-times"></span> Cancel (abandon changes)</a>
    </div>
  </form>

{% endblock %}

prod/templates/prod/product_composition_list.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
  Product List
{% endblock %}


{% block page_content %}
  <h1>Product Composition List</h1>

  {% comment %}
  {% if perms.prod.product_create %}
    <p>
      <a href={% url "prod:product-create" %}><span class="fa fa-plus"></span> Create</a>
    </p>
  {% endif %}
  {% endcomment %}

{% if object_list %}
  <table class="table">
    <tr>
      <th>Up</th>
      <th>Product</th>
      <th>Note</th>
      <th>Weight Initial</th>
      <th>#</th>
    </tr>

    {% for rec in object_list %}
      <tr>
        <td>{{ rec.up }}</td>
        <td>{{ rec.product }}</td>
        <td>{{ rec.note }}</td>
        <td>{{ rec.weight_initial }}</td>
        <td>
{#          <{% if perms.prod.product_update %} #}
{#            <a href={% url "prod:product-update" pk=rec.id %}>{{ rec.id }}</a> #}
{#          {% else %} #}
            {{ rec.id }}
{#          {% endif %} #}
        </td>
        {% for r in rec.fields %}
          {{ r.label }}
        {% endfor %}
      </tr>
    {% endfor %}
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}
{% endblock %}

prod/templates/prod/product_composition_saved.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
  Product Composition
{% endblock %}

{% block page_content %}

  <h1>Product Composition</h1>

  <form method="post">{% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <span class="help-inline text-danger">{{ error }}</span>
        {% endfor %}
        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}

    <div class="form-group">
      <button type="success" class="btn btn-outline-success"><span class="fa fa-check"></span> Submit</button>
      <a href="{% url 'prod:product-composition-list' %}" class="btn btn-outline-secondary"><span class="fa fa-times"></span> Cancel (abandon changes)</a>
    </div>

  </form>

{% endblock %}

prod/templates/prod/product_list.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
  Product List
{% endblock %}


{% block page_content %}
  <h1>Product List</h1>

  {% if perms.prod.product_create %}
    <p>
      <a href={% url "prod:product-create" %}><span class="fa fa-plus"></span> Create</a>
    </p>
  {% endif %}

{% if object_list %}
  <table class="table">
    <tr>
      <th>Name</th>
      <!-- <th>Note</th> -->
      <th>Type</th>
      <th>Code</th>
      <th>#</th>
    </tr>
  {% for rec in object_list %}
    <tr>
      <td>{{ rec.name }}</td>
      <!-- <td>{{ rec.note }}</td> -->
      <td>{{ rec.product_type }}</td>
      <td>{{ rec.code }}</td>
      <td>
        {% if perms.prod.product_update %}
          <a href={% url "prod:product-update" pk=rec.id %}>{{ rec.id }}</a>
        {% else %}
          {{ rec.id }}
        {% endif %}
      </td>
    </tr>
  {% endfor %}
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}
{% endblock %}

prod/templates/prod/product_type.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
  Product Type
{% endblock %}


{% block page_content %}
  <h1>Product Type</h1>

  <form method="post">{% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field|add_class:'form-control' }}
      {% for error in field.errors %}
        <span class="help-inline text-danger">{{ error }}</span>
      {% endfor %}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

  <div class="form-group">
    <button type="success" class="btn btn-outline-success"><span class="fa fa-check"></span> Submit</button>
    <a href="{% url 'prod:product-type-list' %}" class="btn btn-outline-secondary"><span class="fa fa-times"></span> Cancel (abandon changes)</a>
  </div>
</form>

{% endblock %}

prod/templates/prod/product_type_list.html
{% extends "base_site.html" %}
{% load widget_tweaks %}
{% load i18n static %}

{% block page_title %}
  Product Type List
{% endblock %}


{% block page_content %}
  <h1>Product Type List</h1>

  {% if perms.prod.product_type_create %}
    <p>
      <a href={% url "prod:product-type-create" %}><span class="fa fa-plus"></span> Create</a>
    </p>
  {% endif %}

{% if object_list %}
  <table class="table">
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Show Order</th>
      <th>#</th>
    </tr>
  {% for rec in object_list %}
    <tr>
      <td>{{ rec.code }}</td>
      <td>{{ rec.name }}</td>
      <td>{{ rec.show_order }}</td>
      <td>
        {% if perms.prod.product_type_update %}
          <a href={% url "prod:product-type-update" pk=rec.id %}>{{ rec.id }}</a>
        {% else %}
          {{ rec.id }}
        {% endif %}
      </td>
    </tr>
  {% endfor %}
    </table>
  {% else %}
    {% trans "No records" %}
  {% endif %}
{% endblock %}